---
title: "Explorations"
author: "Alejandra Garcia Isaza"
date: '2022-10-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(haven)
library(janitor)
library(knitr)
library(surveytoolbox)
library(sjPlot)
library(kableExtra)
library(psych)
library(sjmisc)
library(MVN)

theme_set(theme_minimal())
```

# Loading the dataset
```{r}
d <- read_sav(here("nopublish", "PARQ.Stacked.sav"))
```
# Initial cleaning & filtering
```{r}

d2 <- d %>%
  filter(wave == 1 | wave == 2)

# find a way to filter all moms and dad if mom is not present. Look at, select if... if not...
```



--------------------------
## EFA decisions 
--------------------------

# Homework Involvement (17) -- JUNTOS as model
```{r eval=FALSE}
# # Homework Involvement (17)
# scale_7 <- efa_vars %>%
#   select(q82_p1:q98_p1)
# 
# # Poly corr matrix
# poly_scale_7 <- polychoric(scale_7)
# poly_scale_7_mat <- data.frame(poly_scale_7$rho)
# 
# # scree plot
# scree(poly_scale_7_mat,factors=TRUE,pc=FALSE,main="Scree plot",hline=NULL,add=FALSE)
# 
# # EFA
# fa(scale_7, n.obs = NA, rotate = "none", fm = "uls", cor = "poly")
```

```{r eval=FALSE}
#removing 82, 83, 92
# scale_7.1 <- efa_vars %>%
#   select(q84_p1:q91_p1, q93_p1:q98_p1)
# 
# # PARALLEL ANALYSIS - Homework Involvement (17)
# fa.parallel(scale_7.1, n.obs=NULL, fm="uls", fa="fa", nfactors=1, main="Parallel Analysis Scree Plots", n.iter=20, error.bars=FALSE, se.bars=FALSE, SMC=FALSE, ylabel=NULL, show.legend=TRUE, sim=TRUE, quant=.95, cor="poly", use="pairwise", plot=TRUE, correct=.5) # parrallel analysis suggest 4 factors
# 
# # 4 factors
# fa(scale_7.1, nfactors = 4, n.obs = NA, rotate = "quartimin", fm = "uls", cor = "poly")
# 
# # 3 factors
# fa(scale_7.1, nfactors = 3, n.obs = NA, rotate = "quartimin", fm = "uls", cor = "poly")
```

```{r eval=FALSE}
#Reliability: Homework Involvement (17)
# scale_7.1_fa_1 <- efa_vars %>%
#   select(q86_p1:q89_p1, q94_p1, q96_p1, q97_p1)
# 
# alpha(scale_7.1_fa_1) # 0.78
# 
# scale_7.1_fa_2 <- efa_vars %>%
#   select(q84_p1, q85_p1, q93_p1, q95_p1)
# 
# alpha(scale_7.1_fa_2) # 0.70 (0.77 if removing 95)
# 
# scale_7.1_fa_3 <- efa_vars %>%
#   select(q90_p1, q91_p1, q98_p1) 
# 
# alpha(scale_7.1_fa_3) # 0.59
```

